// Code generated by github.com/izumin5210/grapi. DO NOT EDIT.

package server

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"

	"grpc-account-svc/api"
)

// RegisterWithServer implements grapiserver.Server.RegisterWithServer.
func (s *accountServiceServerImpl) RegisterWithServer(grpcSvr *grpc.Server) {
	api.RegisterAccountServiceServer(grpcSvr, s)
}

// RegisterWithHandler implements grapiserver.Server.RegisterWithHandler.
func (s *accountServiceServerImpl) RegisterWithHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return api.RegisterAccountServiceHandler(ctx, mux, conn)
}
