// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account_Status int32

const (
	Account_ACTIVE  Account_Status = 0
	Account_BLOCKED Account_Status = 1
	Account_DORMANT Account_Status = 2
)

var Account_Status_name = map[int32]string{
	0: "ACTIVE",
	1: "BLOCKED",
	2: "DORMANT",
}

var Account_Status_value = map[string]int32{
	"ACTIVE":  0,
	"BLOCKED": 1,
	"DORMANT": 2,
}

func (x Account_Status) String() string {
	return proto.EnumName(Account_Status_name, int32(x))
}

func (Account_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0, 0}
}

type Balance_Type int32

const (
	Balance_CURRENT   Balance_Type = 0
	Balance_AVAILABLE Balance_Type = 1
)

var Balance_Type_name = map[int32]string{
	0: "CURRENT",
	1: "AVAILABLE",
}

var Balance_Type_value = map[string]int32{
	"CURRENT":   0,
	"AVAILABLE": 1,
}

func (x Balance_Type) String() string {
	return proto.EnumName(Balance_Type_name, int32(x))
}

func (Balance_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1, 0}
}

type Account struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string               `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Nickname             string               `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ProdCode             string               `protobuf:"bytes,4,opt,name=prod_code,json=prodCode,proto3" json:"prod_code,omitempty"`
	ProdName             string               `protobuf:"bytes,5,opt,name=prod_name,json=prodName,proto3" json:"prod_name,omitempty"`
	Currency             string               `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Servicer             string               `protobuf:"bytes,7,opt,name=servicer,proto3" json:"servicer,omitempty"`
	Status               Account_Status       `protobuf:"varint,8,opt,name=status,proto3,enum=svc.accounts.Account_Status" json:"status,omitempty"`
	StatusLastUpdated    *timestamp.Timestamp `protobuf:"bytes,9,opt,name=status_last_updated,json=statusLastUpdated,proto3" json:"status_last_updated,omitempty"`
	Balances             []*Balance           `protobuf:"bytes,10,rep,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Account) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Account) GetProdCode() string {
	if m != nil {
		return m.ProdCode
	}
	return ""
}

func (m *Account) GetProdName() string {
	if m != nil {
		return m.ProdName
	}
	return ""
}

func (m *Account) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Account) GetServicer() string {
	if m != nil {
		return m.Servicer
	}
	return ""
}

func (m *Account) GetStatus() Account_Status {
	if m != nil {
		return m.Status
	}
	return Account_ACTIVE
}

func (m *Account) GetStatusLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.StatusLastUpdated
	}
	return nil
}

func (m *Account) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

type Balance struct {
	Amount               float64              `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 Balance_Type         `protobuf:"varint,2,opt,name=type,proto3,enum=svc.accounts.Balance_Type" json:"type,omitempty"`
	CreditFlag           bool                 `protobuf:"varint,3,opt,name=credit_flag,json=creditFlag,proto3" json:"credit_flag,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Balance) GetType() Balance_Type {
	if m != nil {
		return m.Type
	}
	return Balance_CURRENT
}

func (m *Balance) GetCreditFlag() bool {
	if m != nil {
		return m.CreditFlag
	}
	return false
}

func (m *Balance) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type GetAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func init() {
	proto.RegisterEnum("svc.accounts.Account_Status", Account_Status_name, Account_Status_value)
	proto.RegisterEnum("svc.accounts.Balance_Type", Balance_Type_name, Balance_Type_value)
	proto.RegisterType((*Account)(nil), "svc.accounts.Account")
	proto.RegisterType((*Balance)(nil), "svc.accounts.Balance")
	proto.RegisterType((*GetAccountRequest)(nil), "svc.accounts.GetAccountRequest")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x93, 0xd4, 0x49, 0x26, 0x6d, 0x94, 0x2e, 0x6a, 0x65, 0xb9, 0x85, 0x46, 0x3e, 0xe5,
	0x64, 0x83, 0xe1, 0xca, 0xc1, 0x49, 0x43, 0x15, 0x08, 0x89, 0xe4, 0xba, 0x3d, 0x70, 0x89, 0x36,
	0xf6, 0x36, 0xb2, 0x70, 0xbc, 0xc6, 0xbb, 0xae, 0x14, 0x21, 0x2e, 0xfc, 0x02, 0x9f, 0xc1, 0x87,
	0xf0, 0x01, 0x88, 0x3f, 0xe0, 0x43, 0x90, 0x77, 0x37, 0x0d, 0x49, 0x8b, 0xb8, 0x79, 0xe6, 0xbd,
	0xb7, 0x33, 0xf3, 0x66, 0x0c, 0x87, 0x38, 0x0c, 0x69, 0x91, 0x72, 0x3b, 0xcb, 0x29, 0xa7, 0xe8,
	0x80, 0xdd, 0x85, 0xb6, 0x4a, 0x31, 0xf3, 0x7c, 0x41, 0xe9, 0x22, 0x21, 0x8e, 0xc0, 0xe6, 0xc5,
	0xad, 0xc3, 0xe3, 0x25, 0x61, 0x1c, 0x2f, 0x33, 0x49, 0x37, 0xcf, 0x14, 0x01, 0x67, 0xb1, 0x83,
	0xd3, 0x94, 0x72, 0xcc, 0x63, 0x9a, 0x32, 0x85, 0x9e, 0xee, 0xca, 0xc9, 0x32, 0xe3, 0x2b, 0x09,
	0x5a, 0xdf, 0xab, 0x50, 0xf7, 0x64, 0x21, 0xd4, 0x86, 0x4a, 0x1c, 0x19, 0x5a, 0x57, 0xeb, 0x35,
	0xfd, 0x4a, 0x1c, 0xa1, 0xa7, 0x00, 0xaa, 0x87, 0x59, 0x1c, 0x19, 0x15, 0x91, 0x6f, 0xaa, 0xcc,
	0x28, 0x42, 0x26, 0x34, 0xd2, 0x38, 0xfc, 0x98, 0xe2, 0x25, 0x31, 0xaa, 0x02, 0xbc, 0x8f, 0xd1,
	0x29, 0x34, 0xb3, 0x9c, 0x46, 0xb3, 0x90, 0x46, 0xc4, 0xa8, 0x49, 0xb0, 0x4c, 0x0c, 0x68, 0xb4,
	0x01, 0x85, 0x72, 0x7f, 0x03, 0x4e, 0x4a, 0xa5, 0x09, 0x8d, 0xb0, 0xc8, 0x73, 0x92, 0x86, 0x2b,
	0x43, 0x97, 0xd8, 0x3a, 0x2e, 0x31, 0x46, 0xf2, 0xbb, 0x38, 0x24, 0xb9, 0x51, 0x97, 0xd8, 0x3a,
	0x46, 0xaf, 0x40, 0x67, 0x1c, 0xf3, 0x82, 0x19, 0x8d, 0xae, 0xd6, 0x6b, 0xbb, 0x67, 0xf6, 0xdf,
	0x1e, 0xda, 0x6a, 0x46, 0xfb, 0x4a, 0x70, 0x7c, 0xc5, 0x45, 0x6f, 0xe1, 0x89, 0xfc, 0x9a, 0x25,
	0x98, 0xf1, 0x59, 0x91, 0x45, 0x98, 0x93, 0xc8, 0x68, 0x76, 0xb5, 0x5e, 0xcb, 0x35, 0x6d, 0xe9,
	0x9c, 0xbd, 0x76, 0xce, 0x0e, 0xd6, 0xc6, 0xfb, 0x47, 0x52, 0x36, 0xc6, 0x8c, 0x5f, 0x4b, 0x11,
	0x7a, 0x01, 0x8d, 0x39, 0x4e, 0x70, 0x1a, 0x12, 0x66, 0x40, 0xb7, 0xda, 0x6b, 0xb9, 0xc7, 0xdb,
	0x3d, 0xf4, 0x25, 0xea, 0xdf, 0xd3, 0x2c, 0x1b, 0x74, 0xd9, 0x10, 0x02, 0xd0, 0xbd, 0x41, 0x30,
	0xba, 0x19, 0x76, 0xf6, 0x50, 0x0b, 0xea, 0xfd, 0xf1, 0x74, 0xf0, 0x6e, 0x78, 0xd1, 0xd1, 0xca,
	0xe0, 0x62, 0xea, 0xbf, 0xf7, 0x26, 0x41, 0xa7, 0x62, 0xfd, 0xd2, 0xa0, 0xae, 0x5e, 0x41, 0x27,
	0xa0, 0xe3, 0x65, 0xf9, 0xb0, 0xd8, 0x98, 0xe6, 0xab, 0x08, 0xd9, 0x50, 0xe3, 0xab, 0x8c, 0x88,
	0x7d, 0xb5, 0x5d, 0xf3, 0xd1, 0x16, 0xec, 0x60, 0x95, 0x11, 0x5f, 0xf0, 0xd0, 0x39, 0xb4, 0xc2,
	0x9c, 0x44, 0x31, 0x9f, 0xdd, 0x26, 0x78, 0x21, 0x36, 0xd9, 0xf0, 0x41, 0xa6, 0xde, 0x24, 0x78,
	0x81, 0x5e, 0xc3, 0xc1, 0x96, 0x39, 0xb5, 0xff, 0x9a, 0xd3, 0x4a, 0x36, 0xb6, 0x58, 0x16, 0xd4,
	0xca, 0x6a, 0xe5, 0x20, 0x83, 0x6b, 0xdf, 0x1f, 0x4e, 0x82, 0xce, 0x1e, 0x3a, 0x84, 0xa6, 0x77,
	0xe3, 0x8d, 0xc6, 0x5e, 0x7f, 0x3c, 0xec, 0x68, 0x96, 0x0b, 0x47, 0x97, 0x84, 0xab, 0x1d, 0xf9,
	0xe4, 0x53, 0x41, 0x18, 0xdf, 0x39, 0x3f, 0x6d, 0xe7, 0xfc, 0xdc, 0x1f, 0x1a, 0xb4, 0x95, 0xe2,
	0x4a, 0x1e, 0x01, 0x8a, 0x00, 0x36, 0xcf, 0xa0, 0xf3, 0xed, 0xd1, 0x1f, 0x14, 0x30, 0x8f, 0x1f,
	0x3d, 0x11, 0xeb, 0xd9, 0xd7, 0x9f, 0xbf, 0xbf, 0x55, 0x0c, 0x74, 0xe2, 0xac, 0x21, 0xe7, 0xf3,
	0xa6, 0x91, 0x2f, 0x68, 0x0a, 0xed, 0x4b, 0xc2, 0x03, 0x9a, 0x29, 0x01, 0x43, 0x27, 0x0f, 0xbc,
	0x18, 0x96, 0xbf, 0xd8, 0xbf, 0x0a, 0x1c, 0x88, 0x02, 0x3a, 0xaa, 0x39, 0x9c, 0x66, 0xcf, 0xb5,
	0xfe, 0xfe, 0x87, 0x2a, 0xce, 0xe2, 0xb9, 0x2e, 0xd4, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x42, 0x9b, 0xaa, 0x41, 0x0c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	GetTopAccounts(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (AccountService_GetTopAccountsClient, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/svc.accounts.AccountService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetTopAccounts(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (AccountService_GetTopAccountsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AccountService_serviceDesc.Streams[0], "/svc.accounts.AccountService/GetTopAccounts", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountServiceGetTopAccountsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AccountService_GetTopAccountsClient interface {
	Recv() (*Account, error)
	grpc.ClientStream
}

type accountServiceGetTopAccountsClient struct {
	grpc.ClientStream
}

func (x *accountServiceGetTopAccountsClient) Recv() (*Account, error) {
	m := new(Account)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	GetTopAccounts(*empty.Empty, AccountService_GetTopAccountsServer) error
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) GetAccount(ctx context.Context, req *GetAccountRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (*UnimplementedAccountServiceServer) GetTopAccounts(req *empty.Empty, srv AccountService_GetTopAccountsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTopAccounts not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svc.accounts.AccountService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetTopAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountServiceServer).GetTopAccounts(m, &accountServiceGetTopAccountsServer{stream})
}

type AccountService_GetTopAccountsServer interface {
	Send(*Account) error
	grpc.ServerStream
}

type accountServiceGetTopAccountsServer struct {
	grpc.ServerStream
}

func (x *accountServiceGetTopAccountsServer) Send(m *Account) error {
	return x.ServerStream.SendMsg(m)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "svc.accounts.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _AccountService_GetAccount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTopAccounts",
			Handler:       _AccountService_GetTopAccounts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "account.proto",
}
